### ISSUE TITLE
OverwatchArcade.Today - breaking API

### ISSUE THREAD

**Issue by Quintenps** [scottschroeder/ow-arcade-bot#1]
Hi Scott,

It seems that you're using the OverwatchArcade.Today API.
Just wanted to quickly let you know that we will be soon releasing our new application which will have API breaking changes.

We will most likely launch the new website on the 24th, that'll give developers some time to refactor to the new API.
There is a beta/testing version available at https://beta.overwatcharcade.today, you can find and test the API there.

Thanks :)

**Comment by scottschroeder** [comment]
Thanks for letting me know! Closed in 79d21168c30caf0b77e61e2e34819550b2834d09.
